FROM node:24.13.0-alpine AS base

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN corepack enable && pnpm install --frozen-lockfile

COPY . .

EXPOSE 4545

CMD ["node", "--experimental-strip-types", "./services/code-intel-mcp/src/server.ts"]
